version: "2"
services:
  lava-master:
    hostname: lava-master
    restart: always
    build:
      context: ./
      args:
        admin_username: "admin"
        admin_password: "password"
        admin_email: "admin@localhost.com"
    ports:
    - "80:80"           # http
    - "5555:5555"       # master
    - "5556:5556"       # logger
